import { Table } from "react-bootstrap";

import { KaTeX } from "@sssp/components";

import styles from "./AboutPage.module.scss";

const AboutPage: React.FC = () => (
  <div id={styles.aboutPage}>
    <header className="page-title">
      <h1 className="display-6">
        Standard Solid-State Pseudopotentials (SSSP)
      </h1>
    </header>

    <main>
      <section>
        <p>
          The Standard Solid-State Pseudopotentials (SSSP) library is a
          carefully curated pseudopotential set for precision or efficiency. Its
          four libraries (SSSP PBE Efficiency, SSSP PBE Precision, SSSP PBEsol
          Efficiency and SSSP PBEsol Precision) cover for each element either
          the best-in-class pseudopotential (among many libraries, or generated
          by us), or occasionally allow for a compromise (either expensive and
          accurate, or less expensive and a bit less accurate).
        </p>
        <p>
          Systematic verifications, described below, are performed on the SSSP
          PBE libraries, with the same generation parameters subsequently used
          to produce the corresponding PBEsol pseudopotentials.
        </p>
        <p>
          Both the transferability and convergence behaviors of the
          pseudopotentials are used as key metrics to determine which
          pseudopotentials are included in the final libraries. Detailed
          definitions and discussions of these metrics can be found in the{" "}
          <a href="" target="_blank">
            SSSP reference paper
          </a>
          . Below, we provide an overview of the criteria used.
        </p>
      </section>
      <section>
        <h4>Transferability</h4>
        <ul>
          <li>
            Equation of State (EOS): The equation of state (EOS) is computed
            following the ACWF protocol (Bosoni et al., 2024) and compared with
            reference all-electron WIEN2k/FLEUR results from the corresponding
            benchmark study.
          </li>
          <li>
            Band Structure and Ghost-State Check: Band structures are calculated
            along the high-symmetry path generated by seekpath. For each
            selected pseudopotential, we verify the absence of ghost states up
            to 10 eV above the Fermi level.
          </li>
        </ul>
        <p>
          For convergence verification, the Quantum ESPRESSO parameters follow
          those reported by Gabriel de Miranda Nascimento et al. (
          <a href="https://arxiv.org/pdf/2504.03962" target="_blank">
            2025, arXiv:2504.03962
          </a>
          ). The convergence tests are carried out across five material
          properties:
        </p>
        <ul>
          <li>
            The convergence of the cohesive energy, δE<sub>coh</sub>, with
            respect to the converged value
          </li>
          <li>
            The discrepancy of all phonon frequencies, δω̄, at the zone boundary,
            with respect to the converged value
          </li>
          <li>
            The convergence of the bands structure, η<sub>10</sub> and max η
            <sub>10</sub> with respect to the converged value
          </li>
          <li>
            The convergence of the pressure, δV<sub>press</sub>, with respect to
            the converged value
          </li>
          <li>
            The delta value of the equation of state, δμ of EOS (error compared
            with the average of two all-electron WIEN2k/FLEUR results), at the
            fully converged cutoff
          </li>
        </ul>
        <p>
          The recommended wave-function and charge-density cutoffs are indicated
          in the periodic table for each element with the chosen
          pseudopotentials. Recommended cutoff values are obtained by first
          performing convergence tests for the wave-function cutoff, then
          performing similar tests for the charge-density cutoff with the
          wave-function cutoff fixed at the converged value.
        </p>
        <p>
          Charge-density cutoff convergence is examined using a finer grid of
          test values. For norm-conserving pseudopotentials, the charge-density
          cutoff (ecutrho) is tested starting from a dual of 4 (i.e., ecutrho =
          4 x ecutwfc) down to a dual of 1, with a stepsize of 0.5. For
          ultrasoft/PAW pseudopotentials, the dual is varied from 8 to 2, again
          with a stepsize of 0.5. The only exceptions are Mn , Hf, Ni, Co, Fe
          and O, where the dual ranges from 18 to 4 due to their more demanding
          electronic structure.
        </p>
        <p>
          All tests are performed using PBE pseudopotentials within the Quantum
          ESPRESSO package. Based on the convergence results, the final
          charge-density cutoff values are selected manually.
        </p>
      </section>
      <section>
        <h4>Baseline of selection criteria for SSSP</h4>
        <p>
          The table below summarizes the baseline selection criteria. For
          efficiency, some pseudopotentials are chosen with relaxed requirements
          to reduce computational cost, while for precision, stricter criteria
          ensure consistently accurate results.
        </p>
        <Table
          id={styles["selection-criteria-table"]}
          striped
          bordered
          responsive
        >
          <thead>
            <tr>
              <th></th>
              <th>SSSP Efficiency</th>
              <th>SSSP Precision</th>
              <th>Notes</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Phonon frequencies (δω̄)</td>
              <td>&lt; 2%</td>
              <td>&lt; 1%</td>
              <td></td>
            </tr>
            <tr>
              <td>
                Cohesive energy (δE<sub>coh</sub>)
              </td>
              <td>&lt; 1 meV/atom</td>
              <td>&lt; 0.5 meV/atom</td>
              <td></td>
            </tr>
            <tr>
              <td>
                Pressure (δV<sub>press</sub>)
              </td>
              <td>&lt; 1%</td>
              <td>&lt; 0.5%</td>
              <td>In terms of volume differences</td>
            </tr>
            <tr>
              <td>
                Bands (η<sub>10</sub>)
              </td>
              <td>&lt; 10 meV</td>
              <td>&lt; 5 meV</td>
              <td>In selection, we are not rigorous with bands.</td>
            </tr>
            <tr>
              <td>
                Bands (max η<sub>10</sub>)
              </td>
              <td>&lt; 20 meV</td>
              <td>&lt; 10 meV</td>
              <td>In selection, we are not rigorous with bands.</td>
            </tr>
            <tr>
              <td>Equation of state (ν-metric)</td>
              <td>&lt; 0.2</td>
              <td>&lt; 0.1</td>
              <td></td>
            </tr>
          </tbody>
        </Table>
        <p>
          Please note that for the SSSP Precision libraries, we often
          conservatively choose pseudopotentials with semi-core states in the
          valence; this greatly increases the cost of the calculations if many
          atoms of such elements are used, and might not be needed in bulk
          metallic solids.
        </p>
      </section>

      <section>
        <h4>Computational details</h4>
        <p>
          We provide here the computational details for the convergence tests
          and the transferability tests. For more details, please refer to the{" "}
          <a href="" target="_blank">
            SSSP reference paper
          </a>
          .
        </p>
        <h6>Input Structures</h6>
        <ul>
          <li>
            Δ: most stable elemental system (
            <a href="http://molmod.ugent.be/deltacodesdft" target="_blank">
              Cottenier's work
            </a>{" "}
            and rare-earth nitrides from Topsakal-Wentzkovitch work).
          </li>
          <li>
            Phonon, pressure, cohesive energy: Cottenier's structures (except
            SiF4, which was used for F due to convergence issues) and rare-earth
            nitrides.
          </li>
          <li>
            Bands: Cottenier's structures reduced to primitive cells (except
            SiF4, which was used for F due to convergence issues) and rare-earth
            nitrides.
          </li>
        </ul>
        <h6>Δ calculations</h6>
        <ul>
          <li>Wave function cutoffs: 200 Ry</li>
          <li>Dual = 8 (PAW/US), 4 (NC)</li>
          <li>k-points: 20×20×20</li>
          <li>Smearing (degauss): Marzari-Vanderbilt, 0.002 Ry</li>
          <li>
            Non-spin-polarized calculations except Mn (antiferrimagnetic), O and
            Cr (antiferromagnetic), Fe, Co, and Ni (ferromagnetic).
          </li>
        </ul>
        <h6>Phonon, pressure, cohesive energy calculations</h6>
        <ul>
          <li>k-points: 6×6×6; 10×10×10 for oxygen and rare-earth nitrides</li>
          <li>Smearing: Marzari-Vanderbilt, 0.02 Ry</li>
          <li>k-points for isolated atoms: 1×1×1</li>
          <li>Smearing for isolated atoms: Marzari-Vanderbilt, 0.1 Ry</li>
          <li>Unit cell for the isolated atoms: 12×12×12 Å</li>
          <li>q-point: (0.5, 0.5, 0.5).</li>
          <li>All calculations are non-spin-polarized.</li>
        </ul>
        <div style={{ paddingLeft: "1rem" }}>
          <h6>Note</h6>
          <p>The convergence pattern for phonons is calculated as:</p>
          <ul>
            <li>
              Highest frequency &gt; 100 cm<sup>-1</sup> (percentage):
              <KaTeX
                expression={
                  "circle = \\left( \\frac{1}{N} \\sum_{i=1}^N \\left[ \\frac{\\omega_i(\\text{cutoff}) - \\omega_i(200\\text{Ry})}{\\omega_i(200\\text{Ry})} \\right] \\right)^{1/2} \\times 100"
                }
              />
              <KaTeX
                expression={
                  "half\\ error\\ bar = \\max \\left| \\left[ \\frac{\\omega_i(\\text{cutoff}) - \\omega_i(200\\text{Ry})}{\\omega_i(200\\text{Ry})} \\right] \\right| \\times 100"
                }
              />
            </li>
            <li>
              Highest frequency &lt; 100 cm<sup>-1</sup> (absolute value):
              <KaTeX
                expression={
                  "circle = ( \\frac{1}{N} \\sum_{i=1}^N [ \\omega_i(\\text{cutoff}) - \\omega_i(200\\text{Ry}) ]^2 )^{1/2}"
                }
              />
              <KaTeX
                expression={
                  "half\\ error\\ bar = \\max |\\omega_i(\\text{cutoff}) - \\omega_i(200\\text{Ry})|"
                }
              />
            </li>
          </ul>
          <div style={{ paddingLeft: "1rem" }}>
            <p>
              <KaTeX inline expression="N" /> is the total number of frequencies
            </p>
            <p>
              For some elements, we have neglected the first <code>n</code>{" "}
              frequencies in the summation above due to negative frequencies
              and/or strong frequency oscillations as a function of the cutoff
              for all the considered pseudos). We also neglected the first 4
              frequencies for H and I, 12 for N and Cl, 6 for O and SiF4 (which
              replaces F).
            </p>
          </div>
        </div>

        <h6>Bands calculations</h6>
        <ul>
          <li>k-points for the self-consistent calculation: 20×20×20</li>
          <li>k-points for the bands calculation: 6×6×6</li>
          <li>Smearing: Marzari-Vanderbilt, 0.02 Ry;</li>
          <li>All calculations are non-spin-polarized.</li>
        </ul>
      </section>
    </main>
  </div>
);

export default AboutPage;
