import { Table } from "react-bootstrap";

import styles from "./AboutPage.module.scss";

const AboutPage: React.FC = () => (
  <div id={styles["about-page"]}>
    <p>
      The four libraries (SSSP PBE Efficiency, SSSP PBE Precision, SSSP PBEsol
      Efficiency and SSSP PBEsol Precision) cover for each element either the
      best-in-class pseudopotential (among many libraries, or generated by us),
      or occasionally allow for a compromise (either expensive and accurate, or
      less expensive and a bit less accurate).
    </p>
    <p>
      Systematic verifications, described below, are performed on the SSSP PBE
      libraries, with the same generation parameters subsequently used to
      produce the corresponding PBEsol pseudopotentials.
    </p>
    <p>
      Both the transferability and convergence behaviors of the pseudopotentials
      are used as key metrics to determine which pseudopotentials are included
      in the final libraries. Detailed definitions and discussions of these
      metrics can be found in the{" "}
      <a href="" target="_blank">
        corresponding paper
      </a>
      . Below, we provide an overview of the criteria used.
    </p>

    <h3>Transferability</h3>
    <ul>
      <li>
        Equation of State (EOS): The equation of state (EOS) is computed
        following the ACWF protocol (Bosoni et al., 2024) and compared with
        reference all-electron WIEN2k/FLEUR results from the corresponding
        benchmark study.
      </li>
      <li>
        Band Structure and Ghost-State Check: Band structures are calculated
        along the high-symmetry path generated by seekpath. For each selected
        pseudopotential, we verify the absence of ghost states up to 10 eV above
        the Fermi level.
      </li>
    </ul>
    <p>
      For convergence verification, the Quantum ESPRESSO parameters follow those
      reported by Gabriel de Miranda Nascimento et al. (
      <a href="https://arxiv.org/pdf/2504.03962" target="_blank">
        2025, arXiv:2504.03962
      </a>
      ). The convergence tests are carried out across five material properties:
    </p>
    <ul>
      <li>
        The convergence of the cohesive energy, δE<sub>coh</sub>, with respect
        to the converged value
      </li>
      <li>
        The discrepancy of all phonon frequencies, δω̄, at the zone boundary,
        with respect to the converged value
      </li>
      <li>
        The convergence of the bands structure, η<sub>10</sub> and max η
        <sub>10</sub> with respect to the converged value
      </li>
      <li>
        The convergence of the pressure, δV<sub>press</sub>, with respect to the
        converged value
      </li>
      <li>
        The delta value of the equation of state, δμ of EOS (error compared with
        the average of two all-electron WIEN2k/FLEUR results), at the fully
        converged cutoff
      </li>
    </ul>
    <p>
      The recommended wave-function and charge-density cutoffs are indicated in
      the periodic table for each element with the chosen pseudopotentials.
      Recommended cutoff values are obtained by first performing convergence
      tests for the wave-function cutoff, then performing similar tests for the
      charge-density cutoff with the wave-function cutoff fixed at the converged
      value.
    </p>
    <p>
      Charge-density cutoff convergence is examined using a finer grid of test
      values. For norm-conserving pseudopotentials, the charge-density cutoff
      (ecutrho) is tested starting from a dual of 4 (i.e., ecutrho = 4 x
      ecutwfc) down to a dual of 1, with a stepsize of 0.5. For ultrasoft/PAW
      pseudopotentials, the dual is varied from 8 to 2, again with a stepsize of
      0.5. The only exceptions are Mn , Hf, Ni, Co, Fe and O, where the dual
      ranges from 18 to 4 due to their more demanding electronic structure.
    </p>
    <p>
      All tests are performed using PBE pseudopotentials within the Quantum
      ESPRESSO package. Based on the convergence results, the final
      charge-density cutoff values are selected manually.
    </p>

    <h3>Baseline of selection criteria for SSSP</h3>
    <p>
      The table below summarizes the baseline selection criteria. For
      efficiency, some pseudopotentials are chosen with relaxed requirements to
      reduce computational cost, while for precision, stricter criteria ensure
      consistently accurate results.
    </p>
    <Table id={styles["selection-criteria-table"]} striped bordered>
      <thead>
        <tr>
          <th></th>
          <th>SSSP Efficiency</th>
          <th>SSSP Precision</th>
          <th>Notes</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>Phonon frequencies (δω̄)</td>
          <td>&lt; 2%</td>
          <td>&lt; 1%</td>
          <td></td>
        </tr>
        <tr>
          <td>
            Cohesive energy (δE<sub>coh</sub>)
          </td>
          <td>&lt; 1 meV/atom</td>
          <td>&lt; 0.5 meV/atom</td>
          <td></td>
        </tr>
        <tr>
          <td>
            Pressure (δV<sub>press</sub>)
          </td>
          <td>&lt; 1%</td>
          <td>&lt; 0.5%</td>
          <td>In terms of volume differences</td>
        </tr>
        <tr>
          <td>
            Bands (η<sub>10</sub>)
          </td>
          <td>&lt; 10 meV</td>
          <td>&lt; 5 meV</td>
          <td>In selection, we are not rigorous with bands.</td>
        </tr>
        <tr>
          <td>
            Bands (max η<sub>10</sub>)
          </td>
          <td>&lt; 20 meV</td>
          <td>&lt; 10 meV</td>
          <td>In selection, we are not rigorous with bands.</td>
        </tr>
        <tr>
          <td>Equation of state (ν-metric)</td>
          <td>&lt; 0.2</td>
          <td>&lt; 0.1</td>
          <td></td>
        </tr>
      </tbody>
    </Table>
    <p>
      Please note that for the SSSP Precision libraries, we often conservatively
      choose pseudopotentials with semi-core states in the valence; this greatly
      increases the cost of the calculations if many atoms of such elements are
      used, and might not be needed in bulk metallic solids.
    </p>

    <h3>Acknowledgements</h3>
    <p>
      Computational resources for this project were provided by MARVEL (Piz
      Daint at CSCS) and by PRACE (Grant 2016153543).
    </p>
    <hr />
    <p>
      The SSSP library is a verification effort, but it is very important to
      give credit to the different authors that have generated the
      pseudopotential libraries that are tested here, and to the original
      methodological developments that underlie the generation of these
      pseudopotential tables and datasets. Citations can e.g. be taken from this
      list (please contact us if we need to add more), for the libraries,
      methods, and datasets used. Please make an effort to acknowledge these and
      to ensure reproducibility of your calculations by listing/citing all
      pseudopotentials used.
    </p>

    <h4>Verification</h4>
    <ul>
      <li>(placeholder for the prepared paper)</li>
      <li>
        E. Bosoni et al., Nat. Rev. Phys. 6, 45-58 (2024)
        <br />
        <b>DOI:</b>{" "}
        <a
          href="https://www.nature.com/articles/s42254-023-00655-3"
          target="_blank"
        >
          10.1038/s42254-023-00655-3
        </a>
      </li>
      <li>
        SSSP: G. Prandini, A. Marrazzo, I. E. Castelli, N. Mounet and N.
        Marzari, npj Computational Materials 4, 72 (2018)
        <br />
        <b>DOI:</b>{" "}
        <a
          href="https://www.nature.com/articles/s41524-018-0127-2"
          target="_blank"
        >
          10.1038/s41524-018-0127-2
        </a>
        <br />
        <b>WEB:</b>{" "}
        <a href="http://materialscloud.org/sssp" target="_blank">
          http://materialscloud.org/sssp
        </a>
      </li>
      <li>
        K. Lejaeghere et al., Science 351 (6280), 1415 (2016)
        <br />
        <b>DOI:</b>{" "}
        <a
          href="http://science.sciencemag.org/content/351/6280/aad3000"
          target="_blank"
        >
          10.1126/science.aad3000
        </a>
        <br />
        <b>WEB:</b>{" "}
        <a href="http://molmod.ugent.be/deltacodesdft" target="_blank">
          http://molmod.ugent.be/deltacodesdft
        </a>
        <br />
        An open-access copy is available from{" "}
        <a href="http://molmod.ugent.be/deltacodesdft" target="_blank">
          Cottenier's page
        </a>
        .
      </li>
    </ul>

    <h4>Libraries</h4>
    <ul>
      <li>
        GBRV: K. F. Garrity, J. W. Bennett, K. M. Rabe, and D. Vanderbilt,
        Comput. Mater. Sci. 81, 446 (2014).
        <br />
        <b>DOI:</b>{" "}
        <a
          href="http://dx.doi.org/10.1016/j.commatsci.2013.08.053"
          target="_blank"
        >
          10.1016/j.commatsci.2013.08.053
        </a>
        <br />
        <b>WEB:</b>{" "}
        <a href="http://www.physics.rutgers.edu/gbrv" target="_blank">
          http://www.physics.rutgers.edu/gbrv
        </a>
        <br />
        <b>LICENSE:</b> GNU General Public License (version 3).
        <br />
        The UPF file is generated with the conversion from K. Laasonen, A.
        Pasquarello, R. Car, C. Lee, and D. Vanderbilt, Phys. Rev. B 47, 10142
        (1993)
        <br />
        <b>DOI:</b>{" "}
        <a href="https://doi.org/10.1103/PhysRevB.47.10142" target="_blank">
          10.1103/PhysRevB.47.10142
        </a>
      </li>
      <li>
        SG15: M. Schlipf and F. Gygi, Comp. Phys. Comm. 196, 36 (2015)
        <br />
        <b>DOI:</b>{" "}
        <a href="http://dx.doi.org/10.1016/j.cpc.2015.05.011" target="_blank">
          10.1016/j.cpc.2015.05.011
        </a>
        <br />
        <b>WEB:</b>{" "}
        <a
          href="http://www.quantum-simulation.org/potentials/sg15_oncv"
          target="_blank"
        >
          http://www.quantum-simulation.org/potentials/sg15_oncv
        </a>
        <br />
        <b>LICENSE:</b> Creative Commons Attribution-ShareAlike 4.0
        International License (CC BY-SA 4.0).
      </li>
      <li>
        SPMS: Soft and transferable pseudopotentials from multi‑objective
        optimization: M. F. Shojaei, J. E. Pask, A. J. Medford, P.
        Suryanarayana, Comput. Mater. Sci. 226, 39 (2022).
        <br />
        <b>DOI:</b>{" "}
        <a
          href="https://www.sciencedirect.com/science/article/pii/S0010465522003137"
          target="_blank"
        >
          10.1016/j.commatsci.2022.108594
        </a>
      </li>
      <li>
        Goedecker: A. Willand, Y. O. Kvashnin, L. Genovese, A.
        Vázquez-Mayagoitia, A. K. Deb, A. Sadeghi, T. Deutsch, and S. Goedecker,
        J. Chem. Phys. 138, 104109 (2013).
        <br />
        <b>DOI:</b>{" "}
        <a href="http://dx.doi.org/10.1063/1.4793260" target="_blank">
          10.1063/1.4793260
        </a>
        <br />
        <b>WEB:</b>
        <a
          href="http://bigdft.org/Wiki/index.php?title=New_Soft-Accurate_NLCC_pseudopotentials"
          target="_blank"
        >
          http://bigdft.org/Wiki/index.php?title=New_Soft-Accurate_NLCC_pseudopotentials
        </a>
        <br />
        <b>LICENSE:</b> Creative Commons Attribution 3.0 Unported License (CC BY
        3.0).
      </li>
      <li>
        Pslibrary 0.3.1: E. Küçükbenli et al.,{" "}
        <a href="http://arxiv.org/abs/1404.3015" target="_blank">
          arXiv:1404.3015
        </a>
        <br />
        <b>WEB:</b>{" "}
        <a
          href="http://theossrv1.epfl.ch/Main/Pseudopotentials"
          target="_blank"
        >
          http://theossrv1.epfl.ch/Main/Pseudopotentials
        </a>
        <br />
        <b>LICENSE:</b> GNU General Public License (version 2 or later).
      </li>
      <li>
        Pslibrary 1.0.0: A. Dal Corso, Comput. Mater. Sci. 95, 337 (2014).
        <br />
        <b>DOI:</b>{" "}
        <a
          href="http://dx.doi.org/10.1016/j.commatsci.2014.07.043"
          target="_blank"
        >
          10.1016/j.commatsci.2014.07.043
        </a>
        <br />
        <b>WEB:</b>{" "}
        <a
          href="http://www.quantum-espresso.org/pseudopotentials"
          target="_blank"
        >
          http://www.quantum-espresso.org/pseudopotentials
        </a>
        <br />
        <b>LICENSE:</b> GNU General Public License (version 2 or later).
      </li>
      <li>
        RE Wentzcovitch: M. Topsakal and R. M. Wentzcovitch, Comput. Mater. Sci.
        95, 263 (2014)
        <br />
        <b>DOI:</b>{" "}
        <a
          href="http://dx.doi.org/10.1016/j.commatsci.2014.07.030"
          target="_blank"
        >
          10.1016/j.commatsci.2014.07.030
        </a>
        <br />
        <b>WEB:</b>{" "}
        <a
          href="http://www.mineralscloud.com/resources/repaw/index.shtml"
          target="_blank"
        >
          http://www.mineralscloud.com/resources/repaw/index.shtml
        </a>
      </li>
      <li>
        Pseudo Dojo: M.J. van Setten, M. Giantomassi, E. Bousquet, M.J.
        Verstraete, D.R. Hamann, X. Gonze, G.-M. Rignanese, Comp. Phys. Comm.
        226, 39 (2018).
        <br />
        <b>DOI:</b>{" "}
        <a href="https://doi.org/10.1016/j.cpc.2018.01.012" target="_blank">
          10.1016/j.cpc.2018.01.012
        </a>
        <br />
        <b>WEB:</b>{" "}
        <a href="http://www.pseudo-dojo.org/" target="_blank">
          http://www.pseudo-dojo.org/
        </a>
      </li>
      <li>
        Actinides MalteSachs: Malte Sachs, Sergei I. Ivlev, Martin Etter,
        Matthias Conrad, Antti J. Karttunen and Florian Kraus, Inorg. Chem. 60,
        21, 16686-16699 (2021).
        <br />
        <b>DOI:</b>{" "}
        <a href="https://doi.org/10.1021/acs.inorgchem.1c02578" target="_blank">
          10.1021/acs.inorgchem.1c02578
        </a>
      </li>
    </ul>

    <h4>Methods</h4>
    <ul>
      <li>
        Ultrasoft pseudopotentials: D. Vanderbilt, Phys. Rev. B 41, 7892(R)
        (1990).
        <br />
        <b>DOI:</b>{" "}
        <a
          href="http://journals.aps.org/prb/abstract/10.1103/PhysRevB.41.7892"
          target="_blank"
        >
          10.1103/PhysRevB.41.7892
        </a>
        <br />
        <b>WEB:</b>{" "}
        <a href="http://physics.rutgers.edu/~dhv/uspp" target="_blank">
          http://physics.rutgers.edu/~dhv/uspp
        </a>
      </li>
      <li>
        Projector-augmented wave (PAW) method: P. E. Blöchl, Phys. Rev. B 50,
        17953 (1994).
        <br />
        <b>DOI:</b>{" "}
        <a
          href="http://journals.aps.org/prb/abstract/10.1103/PhysRevB.50.17953"
          target="_blank"
        >
          10.1103/PhysRevB.50.17953
        </a>
      </li>
      <li>
        Norm conserving, multiple projectors pseudopotentials: D. R. Hamann,
        Phys. Rev. B 88, 085117 (2013).
        <br />
        <b>DOI:</b>{" "}
        <a
          href="http://journals.aps.org/prb/abstract/10.1103/PhysRevB.88.085117"
          target="_blank"
        >
          10.1103/PhysRevB.88.085117
        </a>
        <br />
        <b>WEB:</b>{" "}
        <a href="http://www.mat-simresearch.com" target="_blank">
          http://www.mat-simresearch.com
        </a>
      </li>
      <li>
        Separable dual-space Gaussian pseudopotentials: S. Goedecker, M. Teter,
        J. Hutter, Phys. Rev. B 54, 1703 (1996).
        <br />
        <b>DOI:</b>{" "}
        <a
          href="http://journals.aps.org/prb/abstract/10.1103/PhysRevB.54.1703"
          target="_blank"
        >
          10.1103/PhysRevB.54.1703
        </a>
        <br />
        <b>WEB:</b>{" "}
        <a href="http://cp2k.web.psi.ch/potentials" target="_blank">
          http://cp2k.web.psi.ch/potentials
        </a>
      </li>
      <li>
        Car-Parrinello molecular dynamics with Vanderbilt ultrasoft
        pseudopotentials
      </li>
    </ul>

    <h4>Other sites</h4>
    <ul>
      <li>
        <a href="http://www.pseudo-dojo.org" target="_blank">
          http://www.pseudo-dojo.org
        </a>
      </li>

      <li>
        <a href="https://dalcorso.github.io/pslibrary/" target="_blank">
          https://dalcorso.github.io/pslibrary/
        </a>
      </li>
    </ul>

    <h3>License</h3>
    <p>
      The SSSP efficiency and precision pseudopotential libraries are a
      collection of pseudopotentials generated by different authors with
      different methodologies, selected according to the SSSP protocol. Each
      single pseudopotential is distributed with its original license (e.g. GPL
      or Creative Commons) as chosen by its authors.
    </p>
    <p>
      By downloading the SSSP efficiency or precision libraries, you accept the
      terms and conditions of the original licenses. Please make an effort to
      acknowledge original authors and to ensure reproducibility of your
      calculations by listing or citing all pseudopotentials used, and being
      compliant with the corresponding licenses. Click here for the
      acknowledgements list.
    </p>

    <h3>Contact</h3>
    <p>
      For any questions, suggestions, or issues regarding the SSSP libraries,
      please contact:
    </p>
    <ul>
      <li>
        <a href="mailto:giovanni.pizzi@psi.ch">Giovanni Pizzi</a>
      </li>
      <li>
        <a href="mailto:jusong.yu@ethz.ch">Jusong Yu</a>
      </li>
      <li>
        <a href="mailto:michail.minotakis@psi.ch">Michail Minotakis</a>
      </li>
      <li>
        <a href="mailto:timo.reents@psi.ch">Timo Reents</a>
      </li>
      <li>
        <a href="mailto:nicola.marzari@psi.ch">Nicola Marzari</a>
      </li>
      <li>
        <a href="mailto:edan.bainglass@psi.ch">Edan Bainglass</a> (SSSP app
        developer)
      </li>
    </ul>

    <p>
      For reporting bugs or issues with the SSSP app, please open an issue on
      the{" "}
      <a
        href="https://github.com/materialscloud-org/discover-sssp-react/issues"
        target="_blank"
      >
        GitHub repository
      </a>
      .
    </p>
    <hr />
    <p>Thank you for using the SSSP app!</p>
  </div>
);

export default AboutPage;
