import { Table } from "react-bootstrap";

import styles from "./AboutPage.module.scss";

const AboutPage: React.FC = () => (
  <div id={styles.aboutPage}>
    <header className="page-title">
      <h1 className="display-6">
        Standard Solid-State Pseudopotentials (SSSP)
      </h1>
    </header>

    <section>
      <p>
        The Standard Solid-State Pseudopotentials (SSSP) library is a carefully
        curated pseudopotential set for precision or efficiency. Its four
        libraries (SSSP PBE Efficiency, SSSP PBE Precision, SSSP PBEsol
        Efficiency and SSSP PBEsol Precision) cover for each element either the
        best-in-class pseudopotential (among many libraries, or generated by
        us), or occasionally allow for a compromise (either expensive and
        accurate, or less expensive and a bit less accurate).
      </p>
      <p>
        Systematic verifications, described below, are performed on the SSSP PBE
        libraries, with the same generation parameters subsequently used to
        produce the corresponding PBEsol pseudopotentials.
      </p>
      <p>
        Both the transferability and convergence behaviors of the
        pseudopotentials are used as key metrics to determine which
        pseudopotentials are included in the final libraries. Detailed
        definitions and discussions of these metrics can be found in the{" "}
        <a href="" target="_blank">
          corresponding paper
        </a>
        . Below, we provide an overview of the criteria used.
      </p>
    </section>

    <section>
      <h4>Transferability</h4>
      <ul>
        <li>
          Equation of State (EOS): The equation of state (EOS) is computed
          following the ACWF protocol (Bosoni et al., 2024) and compared with
          reference all-electron WIEN2k/FLEUR results from the corresponding
          benchmark study.
        </li>
        <li>
          Band Structure and Ghost-State Check: Band structures are calculated
          along the high-symmetry path generated by seekpath. For each selected
          pseudopotential, we verify the absence of ghost states up to 10 eV
          above the Fermi level.
        </li>
      </ul>
      <p>
        For convergence verification, the Quantum ESPRESSO parameters follow
        those reported by Gabriel de Miranda Nascimento et al. (
        <a href="https://arxiv.org/pdf/2504.03962" target="_blank">
          2025, arXiv:2504.03962
        </a>
        ). The convergence tests are carried out across five material
        properties:
      </p>
      <ul>
        <li>
          The convergence of the cohesive energy, δE<sub>coh</sub>, with respect
          to the converged value
        </li>
        <li>
          The discrepancy of all phonon frequencies, δω̄, at the zone boundary,
          with respect to the converged value
        </li>
        <li>
          The convergence of the bands structure, η<sub>10</sub> and max η
          <sub>10</sub> with respect to the converged value
        </li>
        <li>
          The convergence of the pressure, δV<sub>press</sub>, with respect to
          the converged value
        </li>
        <li>
          The delta value of the equation of state, δμ of EOS (error compared
          with the average of two all-electron WIEN2k/FLEUR results), at the
          fully converged cutoff
        </li>
      </ul>
      <p>
        The recommended wave-function and charge-density cutoffs are indicated
        in the periodic table for each element with the chosen pseudopotentials.
        Recommended cutoff values are obtained by first performing convergence
        tests for the wave-function cutoff, then performing similar tests for
        the charge-density cutoff with the wave-function cutoff fixed at the
        converged value.
      </p>
      <p>
        Charge-density cutoff convergence is examined using a finer grid of test
        values. For norm-conserving pseudopotentials, the charge-density cutoff
        (ecutrho) is tested starting from a dual of 4 (i.e., ecutrho = 4 x
        ecutwfc) down to a dual of 1, with a stepsize of 0.5. For ultrasoft/PAW
        pseudopotentials, the dual is varied from 8 to 2, again with a stepsize
        of 0.5. The only exceptions are Mn , Hf, Ni, Co, Fe and O, where the
        dual ranges from 18 to 4 due to their more demanding electronic
        structure.
      </p>
      <p>
        All tests are performed using PBE pseudopotentials within the Quantum
        ESPRESSO package. Based on the convergence results, the final
        charge-density cutoff values are selected manually.
      </p>
    </section>

    <section>
      <h4>Baseline of selection criteria for SSSP</h4>
      <p>
        The table below summarizes the baseline selection criteria. For
        efficiency, some pseudopotentials are chosen with relaxed requirements
        to reduce computational cost, while for precision, stricter criteria
        ensure consistently accurate results.
      </p>
      <Table
        id={styles["selection-criteria-table"]}
        striped
        bordered
        responsive
      >
        <thead>
          <tr>
            <th></th>
            <th>SSSP Efficiency</th>
            <th>SSSP Precision</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Phonon frequencies (δω̄)</td>
            <td>&lt; 2%</td>
            <td>&lt; 1%</td>
            <td></td>
          </tr>
          <tr>
            <td>
              Cohesive energy (δE<sub>coh</sub>)
            </td>
            <td>&lt; 1 meV/atom</td>
            <td>&lt; 0.5 meV/atom</td>
            <td></td>
          </tr>
          <tr>
            <td>
              Pressure (δV<sub>press</sub>)
            </td>
            <td>&lt; 1%</td>
            <td>&lt; 0.5%</td>
            <td>In terms of volume differences</td>
          </tr>
          <tr>
            <td>
              Bands (η<sub>10</sub>)
            </td>
            <td>&lt; 10 meV</td>
            <td>&lt; 5 meV</td>
            <td>In selection, we are not rigorous with bands.</td>
          </tr>
          <tr>
            <td>
              Bands (max η<sub>10</sub>)
            </td>
            <td>&lt; 20 meV</td>
            <td>&lt; 10 meV</td>
            <td>In selection, we are not rigorous with bands.</td>
          </tr>
          <tr>
            <td>Equation of state (ν-metric)</td>
            <td>&lt; 0.2</td>
            <td>&lt; 0.1</td>
            <td></td>
          </tr>
        </tbody>
      </Table>
      <p>
        Please note that for the SSSP Precision libraries, we often
        conservatively choose pseudopotentials with semi-core states in the
        valence; this greatly increases the cost of the calculations if many
        atoms of such elements are used, and might not be needed in bulk
        metallic solids.
      </p>
    </section>
  </div>
);

export default AboutPage;
