import styles from "./LicensePage.module.scss";

const LicensePage: React.FC = () => (
  <div id={styles.licensePage}>
    <header className="page-title">
      <h1 className="display-6">License</h1>
    </header>
    <main>
      <p>
        The SSSP efficiency and precision pseudopotential libraries are a
        collection of pseudopotentials generated by different authors with
        different methodologies, selected according to the SSSP protocol. Each
        single pseudopotential is distributed with its original license (e.g.
        GPL or Creative Commons) as chosen by its authors.
      </p>
      <p>
        By downloading the SSSP efficiency or precision libraries, you accept
        the terms and conditions of the original licenses. Please make an effort
        to acknowledge original authors and to ensure reproducibility of your
        calculations by listing or citing all pseudopotentials used, and being
        compliant with the corresponding licenses. Click here for the
        acknowledgements list.
      </p>
    </main>
  </div>
);

export default LicensePage;
